"""add backtest tables and broker source fields

Revision ID: 4621a4c260c7
Revises: 49afc5fe83d3
Create Date: 2026-03-23 22:00:11.058333
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4621a4c260c7'
down_revision: Union[str, None] = '49afc5fe83d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_run',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.Text(), nullable=False),
    sa.Column('universe_description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('commission_bps', sa.Float(), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('total_costs', sa.Float(), nullable=True),
    sa.Column('nav_series', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('backtest_trade',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('slippage_cost', sa.Float(), nullable=False),
    sa.Column('notional', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index(op.f('ix_backtest_trade_run_id'), 'backtest_trade', ['run_id'], unique=False)
    op.add_column('broker_account_snapshot', sa.Column('source', sa.Text(), nullable=False))
    op.add_column('broker_order_snapshot', sa.Column('source', sa.Text(), nullable=False))
    op.add_column('broker_position_snapshot', sa.Column('source', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_position_snapshot', 'source')
    op.drop_column('broker_order_snapshot', 'source')
    op.drop_column('broker_account_snapshot', 'source')
    op.drop_index(op.f('ix_backtest_trade_run_id'), table_name='backtest_trade')
    op.drop_table('backtest_trade')
    op.drop_table('backtest_run')
    # ### end Alembic commands ###
