"""initial schema with 19 tables

Revision ID: 49afc5fe83d3
Revises: 
Create Date: 2026-03-22 01:48:24.608154
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49afc5fe83d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_account_snapshot',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash_free', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cash_total', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('data_issue',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('issue_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_key', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('exchange_calendar',
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('session_open_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_close_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_extended_hours', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('exchange', 'trade_date')
    )
    op.create_table('instrument',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('issuer_name_current', sa.Text(), nullable=False),
    sa.Column('exchange_primary', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_table('macro_series',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('series_code', sa.String(length=50), nullable=False),
    sa.Column('series_name', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('series_id'),
    sa.UniqueConstraint('series_code')
    )
    op.create_table('source_run',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('counters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('broker_order_snapshot',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('broker_ticker', sa.String(length=30), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('avg_fill_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at_broker', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('broker_position_snapshot',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('broker_ticker', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('corporate_action',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('split_from', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('split_to', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cash_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('earnings_event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('event_time_code', sa.String(length=10), nullable=False),
    sa.Column('eps_estimate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('eps_actual', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('revenue_estimate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('revenue_actual', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('confirmed_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('filing',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('accession_no', sa.String(length=30), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('acceptance_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('primary_doc_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('filing_id'),
    sa.UniqueConstraint('accession_no')
    )
    op.create_table('financial_period',
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('statement_scope', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False, comment='PIT: when this data became publicly available'),
    sa.Column('filing_accession_no', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('financial_period_id')
    )
    op.create_table('instrument_identifier',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('id_type', sa.String(length=30), nullable=False),
    sa.Column('id_value', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'id_type', 'id_value', 'source', 'valid_from'),
    comment='Identifier mapping with temporal validity'
    )
    op.create_table('macro_observation',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('realtime_start', sa.Date(), nullable=False, comment='Vintage start for PIT macro'),
    sa.Column('realtime_end', sa.Date(), nullable=False, comment='Vintage end for PIT macro'),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.series_id'], ),
    sa.PrimaryKeyConstraint('series_id', 'observation_date', 'realtime_start')
    )
    op.create_table('order_intent',
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('target_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('intent_id')
    )
    op.create_table('price_bar_raw',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('vwap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'trade_date', 'source')
    )
    op.create_table('ticker_history',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('issuer_name', sa.Text(), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'ticker', 'effective_from')
    )
    op.create_table('financial_fact_std',
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('statement_type', sa.String(length=20), nullable=False),
    sa.Column('metric_code', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('scale', sa.String(length=20), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_period.financial_period_id'], ),
    sa.PrimaryKeyConstraint('financial_period_id', 'statement_type', 'metric_code', 'source')
    )
    op.create_table('order_draft',
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tif', sa.String(length=10), nullable=False),
    sa.Column('is_live_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['order_intent.intent_id'], ),
    sa.PrimaryKeyConstraint('draft_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_draft')
    op.drop_table('financial_fact_std')
    op.drop_table('ticker_history')
    op.drop_table('price_bar_raw')
    op.drop_table('order_intent')
    op.drop_table('macro_observation')
    op.drop_table('instrument_identifier')
    op.drop_table('financial_period')
    op.drop_table('filing')
    op.drop_table('earnings_event')
    op.drop_table('corporate_action')
    op.drop_table('broker_position_snapshot')
    op.drop_table('broker_order_snapshot')
    op.drop_table('source_run')
    op.drop_table('macro_series')
    op.drop_table('instrument')
    op.drop_table('exchange_calendar')
    op.drop_table('data_issue')
    op.drop_table('broker_account_snapshot')
    # ### end Alembic commands ###
